name: Regression
on:
    push:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    test:
        runs-on: ubuntu-latest

        env:
            TZ: Asia/Tokyo

        strategy:
            matrix:
                python-version: ['3.10']

        steps:
            - uses: actions/checkout@v5

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}

            - name: Set locale
              run: |
                sudo locale-gen ja_JP.UTF-8

            - name: Install Rye
              run: |
                curl -sSf https://rye.astral.sh/get | RYE_NO_AUTO_INSTALL=1 RYE_INSTALL_OPTION="--yes" bash

            - name: Add path of Poetry
              run: echo "$HOME/.rye/shims" >> $GITHUB_PATH

            - name: Cache python modules
              id: cache-python-modules
              uses: actions/cache@v4
              env:
                cache-name: cache-python-modules
              with:
                path: $HOME/.cache
                key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('pyproject.toml') }}
                restore-keys: |
                    ${{ runner.os }}-build-${{ env.cache-name }}-
                    ${{ runner.os }}-build-
                    ${{ runner.os }}-

            - name: Install Dependencies
              run: |
                rye sync

            - name: Run Tests
              run: rye run pytest --cov-report=html -n auto tests/test_basic.py

            - name: Upload coverage file
              uses: actions/upload-artifact@v4
              if: always()
              with:
                name: pytest
                path: tests/evidence

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v4
              with:
                path: tests/evidence

    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: test
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Download test results
              id: deployment
              uses: actions/deploy-pages@v4
